name: Deploy Frontend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test Docker image
        run: docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true cygnetops/react-test npm test -- --coverage
